name: Version
on:
  push:
    branches:
      - main
      - 'support/*'
  pull_request: {}

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: 1.x
      - name: Check version
        # TODO(elippmann): Needs adjustments as soon as we release from (support) branches too.
        run: |
          actual="$(go run cmd/icingadb/main.go --version | head -n1 | sed 's/Icinga DB version: \(.*\)/v\1/')"
          expected="$(git describe --tags $(git rev-list --tags --max-count=1))"
          echo "Actual version:   $actual"
          echo "Expected version: $expected"
          test "$actual" = "$expected" || (echo "Versions do not match"; (exit 1))
